apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: harshapaul265/fe:latest
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 2000 # This is the internal port exposed by the service (inside the cluster)
      targetPort: 3000 # This is the port your container is listening on (e.g., the app runs on port 3000)
      nodePort: 30368 # This is the external port on the Node to expose the service (accessible externally)
  type: NodePort # Exposes the service on a NodePort, making it accessible outside the cluster

