apiVersion: apps/v1
kind: Deployment
metadata:
  name: progress-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: progress-service
  template:
    metadata:
      labels:
        app: progress-service
    spec:
      containers:
        - name: progress-service
          image: harshapaul265/progress-service:latest
          ports:
            - containerPort: 5003
---
apiVersion: v1
kind: Service
metadata:
  name: progress-service
spec:
  selector:
    app: progress-service
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003
      nodePort: 30003
  type: NodePort
