# Use the official Node.js image
FROM node:16

# Set the working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Copy the .env file
COPY .env .env

RUN ls -al /usr/src/app

# Expose the port the app runs on
EXPOSE 5001

# Start the app
CMD ["node", "server.js"]
